version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-cluster
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
#volumes:
#  esdata:
#    driver: local